### ISSUE TITLE
Cannot set property 'NumberOfDecreasesToday' of undefined

### ISSUE THREAD

**Issue by Gerst20051** [mhart/dynalite#123]
I'm getting this issue on the following line:

https://github.com/mhart/dynalite/blob/v3.1.2/actions/createTable.js#L52

`TypeError: Cannot set property 'NumberOfDecreasesToday' of undefined`

**Comment by Gerst20051** [comment]
@mhart do you know where this error is coming from when i try to run locally? i tried making some updates in `dynalite/validations` but haven't found the solution yet if it's coming from there.

https://github.com/mhart/dynalite/blob/master/validations/createTable.js
https://github.com/mhart/dynalite/blob/master/validations/updateTable.js

I tried removing these two lines:

https://github.com/mhart/dynalite/blob/v3.1.3/validations/updateTable.js#L40
https://github.com/mhart/dynalite/blob/v3.1.3/validations/updateTable.js#L83

`ValidationException: 2 validation errors detected: Value null at 'provisionedThroughput' failed to satisfy constraint: Member must not be null; Value null at 'globalSecondaryIndexes.1.member.provisionedThroughput' failed to satisfy constraint: Member must not be null`

Any insight?

**Comment by mhart** [comment]
Can you explain how to reproduce this? Has this only started happening since this PR has been merged?

**Comment by Gerst20051** [comment]
Sure. No this seems to be an issue with the `aws-sdk`. I have two separate files, one for cloudformation and one for local/dynalite since they often need to be different because of incompatibilities. I was trying to make them more similar by removing the `ProvisionedThroughput` section from the local version since it's not needed in the cloudformation definition.

I commented out the validations line to rule that out:

https://github.com/mhart/dynalite/blob/v3.1.3/index.js#L255

Take this resources file:

```
Resources:
  dynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: table-name
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: index_hash_key
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: index-name
          KeySchema:
            - AttributeName: index_hash_key
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
```

The error starts happening locally when you remove the `ProvisionedThroughput` section from the `GlobalSecondaryIndexes` section.
